services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Prasanna@123
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prasanna@123
    ports:
      - "5432:5432"
